# Generated by Django 5.1.7 on 2025-12-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='ID пользователя Telegram')),
                ('categories', models.ManyToManyField(blank=True, to='tasks.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_user_id', 'completed'], name='tasks_task_telegra_eb5b2e_idx'), models.Index(fields=['due_date', 'completed'], name='tasks_task_due_dat_803d27_idx')],
            },
        ),
    ]
